# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  # jobs for building/testing go here
  build:
      docker:
        # specify the version you desire here
        - image: circleci/php:7.1-node-browsers

        # Specify service dependencies here if necessary
        # CircleCI maintains a library of pre-built images
        # documented at https://circleci.com/docs/2.0/circleci-images/
        # - image: circleci/mysql:9.4
      working_directory: ~/tender_bartik
      steps:
        - checkout
        - run: sudo apt install -y libsqlite3-dev zlib1g-dev
        - run: sudo docker-php-ext-install zip
        # Download and cache dependencies
        # Download and cache dependencies
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

        - run: composer install -n --prefer-dist

        - save_cache:
            paths:
              - ./vendor
            key: v1-dependencies-{{ checksum "composer.json" }}
        - run: touch storage/testing.sqlite
        - run: php artisan migrate --env=testing --database=sqlite_testing --force
        - run: ./vendor/bin/codecept build
        - run: ./vendor/bin/codecept run
deployment:
  staging:
    branch: master
    heroku:
      appname: limitless-falls-39048